name: kv_storage_shared_preferences
description: A Flutter implementation of the `KVStorageService` interface using the shared_preferences package.
repository: https://github.com/flutter-news-app-full-source-code/kv-storage-shared-preferences
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  kv_storage_service:
    git:
      url: https://github.com/flutter-news-app-full-source-code/kv-storage-service.git
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
