name: ht_kv_storage_shared_preferences
description: A Very Good Project created by Very Good CLI.
repository: https://github.com/headlines-toolkit/ht-kv-storage-shared-preferences
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  ht_kv_storage_service:
    git:
      url: https://github.com/headlines-toolkit/ht-kv-storage-service.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
